# Generated by Django 4.2.5 on 2023-12-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location1',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
