# Generated by Django 4.2.5 on 2023-12-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_activity_location1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='location1',
        ),
    ]
